# Variables
FRONTEND_DIR := ./frontend
BACKEND_DIR := ./backend

# Define the default target
.PHONY: all
all: run

# Run both backend and frontend simultaneously
.PHONY: run
run:
	@echo "Running Go backend..."
	@cd $(BACKEND_DIR) && go mod tidy && go run main.go types.go server.go webSocketFunctions.go lobbyHandler.go